### PR TITLE
Rename 'type' to 'vct'

### PR DESCRIPTION
**Pull request by danielfett**
This PR renames the claim `type` to `dct`, as per the discussion in #130

### CODE REVIEW

**Review by selfissued — APPROVED** [review]
This is an improvement.

**Review by bc-pi — APPROVED** [review]

**Review by awoie — APPROVED** [review]
We had a good discussion on that already and discussed several options. This is also my favorite option. Thank you!

**Comment by tlodderstedt** [comment]
I oppose against this change. I suggest to use 'vct' instead.

**Review by tlodderstedt — CHANGES_REQUESTED** [review]
I suggest to use 'vct'.

**Comment by selfissued** [comment]
I'm good with `vct`.

For the record, I think it's important to move away from `type`, because https://www.w3.org/TR/vc-data-model/ uses the claim name, but with a different syntax.  Keeping the naming conflict will inevitably lead to grief.

**Review by awoie — CHANGES_REQUESTED** [review]
I'm actually also in favor of `vct`.

**Comment by paulbastian** [comment]
Naming is hard. Regarding dct: isn't it obvious for an internet standard that we refer to digital credentials?

**Comment by Sakurann** [comment]
Neither dct nor vct are intuitive for me, so I am pretty unsure. 

But between dct and vct, I would prefer dct. A term Verifiable credentials got enough feedback that it has strong too strong of an association to W3C VC-DATA-MODEL. And Digital credentials seems to be a term that is acceptable to generalize.

**Comment by awoie** [comment]
> Neither dct nor vct are intuitive for me, so I am pretty unsure.
> 
> But between dct and vct, I would prefer dct. A term Verifiable credentials got enough feedback that it has strong too strong of an association to W3C VC-DATA-MODEL. And Digital credentials seems to be a term that is acceptable to generalize.

Why is "Verifiable Credential Type" (vct) not intuitive to you? This would match the current definition of `type`. Isn't this what this claim is about? That is why I'm actually in favor of `vct` over `dct`, `dty`.

**Comment by Sakurann** [comment]
I meant that abbreviations are not intuitive to me.

And "type" is a pretty JSON-LD specific construct AFAIK so I was hoping we could have a deeper discussion on whether it should be called "claimset" or something. If we are to move away from "type" claim name.

on dct and vct, as I explained, I prefer something that is not associated to W3C VCDM and digital credentials seems to be pretty well understood.

**Comment by bc-pi** [comment]
If the color of the bikeshed is still open for debate, how about just `ct` for credential type?

**Comment by awoie** [comment]
> If the color of the bikeshed is still open for debate, how about just `ct` for credential type?

I like 3-letter-names more than 2-letter-names for some reason. Also, `vct` is more accurate since the spec is about SD-JWT VCs => Verifiable Credentials. I'd be still in favor of `vct` for that reason.

**Comment by danielfett** [comment]
`vct` is fine for me. Updated the PR accordingly.

**Comment by awoie** [comment]
Merging this PR since a lot of approvals. We will have a larger conversation on what is inferred by the `vct` value in a separate issue.

**Pull request merged**
